FROM apache/airflow:2.10.5

COPY requirements-airflow.txt /requirements-airflow.txt
COPY requirements-dbt.txt /requirements-dbt.txt

RUN python -m venv /home/airflow/dbt_venv \
    && /home/airflow/dbt_venv/bin/pip install --no-cache-dir --upgrade pip \
    && /home/airflow/dbt_venv/bin/pip install --no-cache-dir -r /requirements-dbt.txt \
    && pip install --no-cache-dir -r /requirements-airflow.txt